services:
  - name: chikaku-backend
    type: web
    env: node
    rootDir: backend
    repo: https://github.com/AridaneCR/Chikaku_D-D
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000

  - name: chikaku-frontend
    type: static
    rootDir: frontend
    repo: https://github.com/AridaneCR/Chikaku_D-D
    staticPublishPath: "."
